# Generated by Django 2.2 on 2019-04-06 05:32

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256)),
                ('value', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizard.Field')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wizard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MultipleChoiceField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wizard.Field')),
            ],
            options={
                'abstract': False,
            },
            bases=('wizard.field',),
        ),
        migrations.CreateModel(
            name='WizardStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizard.Step')),
                ('wizard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizard.Wizard')),
            ],
            options={
                'unique_together': {('position', 'wizard'), ('wizard', 'step')},
            },
        ),
        migrations.AddField(
            model_name='wizard',
            name='steps',
            field=models.ManyToManyField(through='wizard.WizardStep', to='wizard.Step'),
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('value', django.contrib.postgres.fields.jsonb.JSONField()),
                ('from_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizard.Question')),
                ('to_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggered_by', to='wizard.Question')),
            ],
        ),
        migrations.CreateModel(
            name='StepSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizard.Section')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizard.Step')),
            ],
        ),
        migrations.AddField(
            model_name='step',
            name='sections',
            field=models.ManyToManyField(through='wizard.StepSection', to='wizard.Section'),
        ),
        migrations.CreateModel(
            name='SectionQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizard.Question')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizard.Section')),
            ],
        ),
        migrations.AddField(
            model_name='section',
            name='questions',
            field=models.ManyToManyField(through='wizard.SectionQuestion', to='wizard.Question'),
        ),
        migrations.CreateModel(
            name='RadioButtonFieldOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizard.Option')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='question',
            name='triggers',
            field=models.ManyToManyField(through='wizard.Trigger', to='wizard.Question'),
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', django.contrib.postgres.fields.jsonb.JSONField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='wizard.Question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RadioButtonField',
            fields=[
                ('multiplechoicefield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wizard.MultipleChoiceField')),
                ('required', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('wizard.multiplechoicefield',),
        ),
        migrations.AddConstraint(
            model_name='trigger',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, from_question=django.db.models.expressions.F('to_question')), name='trigger__different_questions'),
        ),
        migrations.AlterUniqueTogether(
            name='trigger',
            unique_together={('to_question', 'from_question', 'value'), ('position', 'from_question')},
        ),
        migrations.AlterUniqueTogether(
            name='stepsection',
            unique_together={('position', 'step'), ('section', 'step')},
        ),
        migrations.AlterUniqueTogether(
            name='sectionquestion',
            unique_together={('question', 'section'), ('position', 'question')},
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('question', 'user')},
        ),
        migrations.AddField(
            model_name='radiobuttonfieldoption',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizard.RadioButtonField'),
        ),
        migrations.AddField(
            model_name='radiobuttonfield',
            name='options',
            field=models.ManyToManyField(through='wizard.RadioButtonFieldOption', to='wizard.Option'),
        ),
        migrations.AlterUniqueTogether(
            name='radiobuttonfieldoption',
            unique_together={('field', 'option'), ('position', 'field')},
        ),
    ]
