# Generated by Django 2.2 on 2019-04-06 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TextField',
            fields=[
                ('field_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wizard.Field')),
                ('maxlength', models.IntegerField(blank=True, null=True)),
                ('minlength', models.IntegerField(blank=True, null=True)),
                ('pattern', models.CharField(blank=True, max_length=256, null=True)),
                ('placeholder', models.CharField(blank=True, max_length=256, null=True)),
                ('readonly', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=False)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('spellcheck', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('wizard.field',),
        ),
    ]
