# Generated by Django 2.2 on 2019-04-06 04:00

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='trigger',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, from_question=django.db.models.expressions.F('to_question')), name='trigger__different_questions'),
        ),
    ]
