# Generated by Django 2.2 on 2019-04-10 20:37

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='field',
            name='default',
        ),
        migrations.AddField(
            model_name='question',
            name='default',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='field',
            name='name',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
