# Generated by Django 2.2 on 2019-04-05 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggered_by', to='wizard.Question'),
        ),
        migrations.AlterUniqueTogether(
            name='radiobuttonoption',
            unique_together={('field', 'label'), ('field', 'value'), ('field', 'position')},
        ),
    ]
