# Generated by Django 2.2 on 2019-04-07 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckboxField',
            fields=[
                ('multiplechoicefield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wizard.MultipleChoiceField')),
                ('exclusive', models.BooleanField(default=False)),
                ('required', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('wizard.multiplechoicefield',),
        ),
        migrations.CreateModel(
            name='CheckboxFieldOption',
            fields=[
                ('multiplechoicefieldoption_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wizard.MultipleChoiceFieldOption')),
                ('position', models.PositiveIntegerField()),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizard.CheckboxField')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wizard.Option')),
            ],
            options={
                'abstract': False,
                'unique_together': {('position', 'field'), ('field', 'option')},
            },
            bases=('wizard.multiplechoicefieldoption',),
        ),
        migrations.AddField(
            model_name='checkboxfield',
            name='options',
            field=models.ManyToManyField(through='wizard.CheckboxFieldOption', to='wizard.Option'),
        ),
    ]
