# Generated by Django 2.2 on 2019-04-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0002_auto_20190407_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkboxfield',
            name='exclusive',
        ),
        migrations.RemoveField(
            model_name='checkboxfield',
            name='required',
        ),
        migrations.AddField(
            model_name='checkboxfieldoption',
            name='exclusive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkboxfieldoption',
            name='required',
            field=models.BooleanField(default=False),
        ),
    ]
