# Generated by Django 2.2 on 2019-04-05 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0002_auto_20190405_0237'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiobuttonfield',
            name='required',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='InputField',
        ),
    ]
