# Generated by Django 2.2 on 2019-04-06 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0002_auto_20190406_0400'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trigger',
            unique_together={('position', 'from_question')},
        ),
    ]
