# Generated by Django 2.2 on 2019-04-06 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0003_auto_20190406_0521'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trigger',
            unique_together={('position', 'from_question'), ('to_question', 'from_question', 'value')},
        ),
    ]
