# Generated by Django 2.2 on 2019-04-07 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0003_auto_20190407_1905'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sectionquestion',
            unique_together={('position', 'question', 'section')},
        ),
    ]
