# Generated by Django 2.2 on 2019-04-05 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0003_auto_20190405_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='wizard.Section'),
        ),
        migrations.AlterUniqueTogether(
            name='question',
            unique_together={('section', 'position')},
        ),
    ]
