# Generated by Django 2.2 on 2019-04-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0004_auto_20190405_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='position',
            field=models.PositiveIntegerField(),
        ),
    ]
