# Generated by Django 2.2 on 2019-04-07 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0004_auto_20190407_1939'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='condition',
            field=models.CharField(choices=[('E', '=='), ('GT', '>'), ('GTE', '>='), ('LT', '<'), ('LTE', '<='), ('IN', 'contained_in')], default='E', max_length=256),
        ),
        migrations.AlterUniqueTogether(
            name='checkboxfieldoption',
            unique_together={('position', 'field', 'option')},
        ),
        migrations.AlterUniqueTogether(
            name='radiobuttonfieldoption',
            unique_together={('position', 'field', 'option')},
        ),
        migrations.AlterUniqueTogether(
            name='stepsection',
            unique_together={('position', 'step', 'section')},
        ),
        migrations.AlterUniqueTogether(
            name='trigger',
            unique_together={('to_question', 'from_question', 'value'), ('position', 'from_question', 'to_question')},
        ),
    ]
