# Generated by Django 2.2 on 2019-04-07 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wizard', '0006_auto_20190407_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='condition',
            field=models.CharField(choices=[('E', 'Value == Answer'), ('GT', 'Value > Answer'), ('GTE', 'Value >= Answer'), ('LT', 'Value < Answer'), ('LTE', 'Value <= Answer'), ('IN', 'Value in Answer')], default='E', max_length=256),
        ),
    ]
